# -*- coding: utf-8 -*-
"""fcc-MAGIC-example

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1of4yYJfgbcVpkt0wv0g_4OteqrBO5wnB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler
from sklearn.naive_bayes import GaussianNB

!pip install sklearn

import sklearn

cols = ["fLength", "fWidth", "fSize", "fConc", "fConc1", "fAsym", "fM3Long", "fM3Trans", "fAlpha", "fDist", "class"]
df = pd.read_csv("magic04.data", names=cols)
df.head()

df["class"] = (df["class"] == "g").astype(int)
df.head()

for label in cols[:-1]:
  plt.hist(df[df["class"]==1][label], color='blue', label='gamma', alpha=0.7, density=True)
  plt.hist(df[df["class"]==0][label], color='red', label='hadron', alpha=0.7, density=True)
  plt.title(label)
  plt.ylabel("Probability")
  plt.xlabel(label)
  plt.legend()
  plt.show()

train, valid, test = np.split(df.sample(frac=1), [int(0.6*len(df)), int(0.8*len(df))])

def scale_dataset(dataframe, oversample=False):
  X = dataframe[dataframe.columns[:-1]].values
  y = dataframe[dataframe.columns[-1]].values

  scaler = StandardScaler()
  X = scaler.fit_transform(X)

  if oversample:
    ros = RandomOverSampler()
    X, y = ros.fit_resample(X, y)

  data = np.hstack((X, np.reshape(y, (-1, 1))))

  return data, X, y

train, X_train, y_train = scale_dataset(train, oversample=True)
valid, X_valid, y_valid = scale_dataset(valid, oversample=False)
test, X_test, y_test = scale_dataset(test, oversample=False)

len(y_train == 1)

sum(y_train == 1)

print(len(train[train['class']==1]))
print(len(train[train['class']==0]))

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

y_pred = knn_model.predict(X_test)

print(classification_report (y_test, y_pred))

y_pred

y_test

from sklearn.naive_bayes import GaussianNB

nb_model= GaussianNB()
nb_model.fit(X_train, y_train)

y_pred = nb_model.predict(X_test)

print(classification_report (y_test, y_pred))

from sklearn.linear_model import LogisticRegression

lg_model= LogisticRegression()
lg_model.fit(X_train, y_train)

y_pred = lg_model.predict(X_test)

print(classification_report (y_test, y_pred))

from sklearn.svm import SVC

svm_model = SVC()
svm_model= svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)
print(classification_report (y_test, y_pred))

def plot_loss(histroy):
  plt.plot(history.history['loss'], label= 'loss')
  plt.plot(history.history['val_loss'], label= 'val_loss')
  plt.xlabel('Epoch')
  plt.ylabel('Binary_crossentropy')
  plt.legend()
  plt.grid(True)
  plt.show()

def plot_accuracy(history):
  plt.plot(history.history['accuracy'], label= 'accuracy')
  plt.plot(history.history['val_accuracy'], label= 'val_accuracy')
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.legend()
  plt.grid(True)

  plt.show()

import tensorflow as tf
nn_model= tf.keras.Sequential({
    tf.keras.layers.Dense(32, activation= 'relu', input_shape= (10,)),
    tf.keras.layers.Dense(32, activation= 'relu'),
    tf.keras.layers.Dense(1, activation= 'sigmoid'),
})
nn_model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss= 'binary_crossentropy', metrics=['accuracy'])

history= nn_model.fit(
    X_train, y_train, epochs=100, batch_size=32, validation_split=0.2
    )

plot_loss(history)
plot_accuracy(history)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import StandardScaler
import copy
import seaborn as sns
import tensorflow as tf
from sklearn.linear_model import LinearRegression

dataset_cols = ["bike_count", "hour", "temp", "humidity", "wind", "visibility", "dew_pt_temp", "radiation", "rain", "snow", "functional"]
df = pd.read_csv("SeoulBikeData.csv")
df.head()